repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["--config=pyproject.toml"]
    files: "({cookiecutter.project_slug}}|tests)"

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--settings-path=pyproject.toml"]
    files: "({cookiecutter.project_slug}}|tests)"

- repo: https://github.com/pycqa/bandit
  rev: 1.7.0
  hooks:
  - id: bandit
    language: python
    language_version: python3
    types: [python]
    files: "({cookiecutter.project_slug}}|tests)"

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
   - id: flake8
     additional_dependencies: [flake8-typing-imports==1.7.0]
     args: ["--max-line-length=80"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    args: ["--ignore-missing-imports"]
    files: "({cookiecutter.project_slug}}|tests)"
