name: examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync --all-groups
      - name: Run tests
        run: |
          uv run python examples/reconciliation.py
